# Generated by Django 4.2.13 on 2024-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('home_number', models.CharField(max_length=255)),
            ],
        ),
    ]
