# Generated by Django 4.2.13 on 2024-07-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
