# Generated by Django 4.2.13 on 2024-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_contract_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='address_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='city_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='city_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='company_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='patronymic_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='patronymic_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='position_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='size_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='size_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='home_number_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='home_number_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='phone_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='phone_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='province_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='province_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='street_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='street_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
