# Generated by Django 4.2.13 on 2024-07-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_contract_address_en_contract_address_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='size_en',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='size_ru',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
