# Generated by Django 4.2.13 on 2024-08-07 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_alter_contract_size_alter_contract_size_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
